" vim-plug: " {{{
"let g:plug_shallow = 0

call plug#begin(g:vimhome . '/bundle/')
Plug 'https://github.com/easymotion/vim-easymotion.git'
Plug 'https://github.com/jremmen/vim-ripgrep.git'
Plug 'junegunn/vim-easy-align'
Plug 'dense-analysis/ale'
Plug 'git@github.com:SethMilliken/gundo.vim.git'
Plug 'git@github.com:SethMilliken/tagbar.git'
Plug 'git@github.com:SethMilliken/tlib_vim.git'
Plug 'git@github.com:SethMilliken/vim-mtg-spell.git'
Plug 'git@github.com:SethMilliken/vim-traitor.git'
Plug 'AndrewRadev/linediff.vim'
Plug 'MarcWeber/vim-addon-async'
Plug 'MarcWeber/vim-addon-manager'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'Raimondi/PickAColor'
Plug 'chrisbra/Colorizer'
Plug 'derekwyatt/vim-scala'
Plug 'godlygeek/tabular'
Plug 'gregsexton/gitv'
Plug 'int3/vim-extradite'
Plug 'jremmen/vim-ripgrep'
Plug 'kana/vim-textobj-function'
Plug 'kana/vim-textobj-user'
Plug 'keith/tmux.vim'
Plug 'kien/ctrlp.vim'
Plug 'lepture/vim-velocity'
Plug 'majutsushi/tagbar'
Plug 'mattn/calendar-vim'
Plug 'mhinz/vim-signify'
Plug 'msanders/cocoa.vim'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'nvie/vim-flake8' " 'pip install flake8'
Plug 'pangloss/vim-javascript'
Plug 'preservim/vim-markdown'
Plug 'rkitover/vimpager'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'sjl/gundo.vim'
Plug 'sjl/splice.vim'
Plug 'slack/vim-l9'
Plug 'smith/javaScriptLint.vim'
Plug 'spiiph/vim-space'
Plug 'tmux-plugins/vim-tmux-focus-events' " 'set -g focus-events on in tmux'
Plug 'tomtom/tlib_vim'
Plug 'tomtom/viki_vim'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-pathogen'
Plug 'tpope/vim-rails'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-ruby/vim-ruby'
Plug 'vim-scripts/FuzzyFinder'
Plug 'vim-scripts/Gist.vim'
Plug 'vim-scripts/ScreenShot'
Plug 'vim-scripts/bufexplorer.zip'
Plug 'vim-scripts/kellys'
Plug 'vim-scripts/matchit.zip'
Plug 'vim-scripts/matrix.vim--Yang'
Plug 'vim-scripts/ruby-matchit'
Plug 'vim-scripts/sessionman.vim'
Plug 'vim-scripts/surround.vim'
Plug 'vim-scripts/xml.vim'
Plug 'vimwiki/vimwiki'
Plug 'weierophinney/paster.vim'
Plug 'yurifury/hexHighlight' " 'brew install jsl'
Plug '~/.vim/bundle/vim-morning-pages/'
Plug '~/.vim/bundle/vim-daily-record/'
"Plug 'https://github.com/VimEz/Tmux.git'
"Plug 'https://github.com/vim-scripts/vimwiki.git'
"Plug 'https://github.com/vim-scripts/vundle.git'
"Plug 'https://github.com/vim-scripts/calendar.vim--Matsumoto.git'
"Plug 'https://github.com/vim-scripts/AnsiEsc.vim.git'
"Plug 'junegunn/vim-easy-align'
"Plug 'https://github.com/vim-scripts/ack.vim.git' " 'brew install ack'
"Plug 'https://github.com/kogakure/vim-sparkup.git'
"Plug 'https://github.com/rstacruz/sparkup.git'
"Plug 'https://github.com/garbas/vim-snipmate.git'
"Plug 'https://github.com/vim-scripts/UltiSnips.git'
"Plug 'https://github.com/dahu/vimple.git'
"Plug 'https://github.com/Raimondi/vim-pathogen.git'
"Plug 'https://github.com/spf13/snipmate.vim.git'
"Plug 'https://github.com/vim-scripts/AutoTag.git'
"Plug 'https://github.com/wincent/Command-T.git' " 'Rebuild if necessary:\n\tpushd command-t/ruby/command-t/; ruby extconf.rb; make && popd'
"Plug 'https://github.com/rson/vim-conque.git'
"Plug 'https://github.com/godlygeek/csapprox.git'
"Plug 'https://github.com/vim-scripts/dbext.vim.git'
"Plug 'https://github.com/Raimondi/delimitMate.git'
"Plug 'https://github.com/serverhorror/javascript.vim.git'
"Plug 'https://github.com/vim-scripts/jslint.vim.git'
"Plug 'https://github.com/puppetlabs/puppet-syntax-vim.git'
"Plug 'https://github.com/vim-scripts/scala.vim.git'
"Plug 'ssh://seth@at.araxia.net/~/git/script-ed.git'
"Plug 'https://github.com/vim-scripts/StatusLineHighlight.git'
"Plug 'https://github.com/sjl/threesome.vim.git'
"Plug 'https://github.com/vim-scripts/TwitVim.git'
"Plug 'https://github.com/MarcWeber/vim-addon-signs.git'
"Plug 'https://github.com/Lokaltog/vim-powerline.git'
"Plug 'https://github.com/markcornick/vim-vagrant.git'

call plug#end()
" }}}
