" vim-plug: " {{{
let g:plug_shallow = 0

call plug#begin(g:vimhome . '/bundle/')
Plug 'junegunn/vim-easy-align'
Plug 'git@github.com:SethMilliken/gundo.vim.git'
Plug 'https://github.com/kogakure/vim-sparkup.git'
Plug 'git@github.com:SethMilliken/tagbar.git'
Plug 'git@github.com:SethMilliken/tlib_vim.git'
Plug 'https://github.com/VimEz/Tmux.git'
Plug 'https://github.com/tpope/vim-abolish.git'
Plug 'https://github.com/vim-scripts/ack.vim.git' " 'brew install ack'
Plug 'https://github.com/vim-scripts/AnsiEsc.vim.git'
Plug 'https://github.com/vim-scripts/bufexplorer.zip.git'
Plug 'https://github.com/vim-scripts/calendar.vim--Matsumoto.git'
Plug 'https://github.com/msanders/cocoa.vim.git'
Plug 'https://github.com/kien/ctrlp.vim.git'
Plug 'https://github.com/int3/vim-extradite.git'
Plug 'https://github.com/tpope/vim-fugitive.git'
Plug 'https://github.com/vim-scripts/FuzzyFinder.git'
Plug 'https://github.com/vim-scripts/Gist.vim.git'
Plug 'https://github.com/gregsexton/gitv.git'
Plug 'https://github.com/sjl/gundo.vim.git'
Plug 'https://github.com/yurifury/hexHighlight.git'
" 'brew install jsl'
Plug 'https://github.com/smith/javaScriptLint.vim.git'
Plug 'https://github.com/vim-scripts/kellys.git'
Plug 'https://github.com/slack/vim-l9.git'
Plug 'https://github.com/AndrewRadev/linediff.vim.git'
Plug 'https://github.com/vim-scripts/matchit.zip.git'
Plug 'https://github.com/vim-scripts/matrix.vim--Yang.git'
Plug 'https://github.com/scrooloose/nerdcommenter.git'
Plug 'https://github.com/scrooloose/nerdtree.git'
Plug 'https://github.com/weierophinney/paster.vim.git'
Plug 'https://github.com/tpope/vim-pathogen.git'
Plug 'https://github.com/Raimondi/PickAColor.git'
Plug 'https://github.com/tpope/vim-rails.git'
Plug 'https://github.com/vim-scripts/ruby-matchit.git'
Plug 'https://github.com/vim-scripts/ScreenShot.git'
Plug 'https://github.com/vim-scripts/sessionman.vim.git'
Plug 'https://github.com/spiiph/vim-space.git'
Plug 'https://github.com/rstacruz/sparkup.git'
Plug 'https://github.com/sjl/splice.vim.git'
Plug 'https://github.com/vim-scripts/surround.vim.git'
Plug 'https://github.com/scrooloose/syntastic.git'
Plug 'https://github.com/godlygeek/tabular.git'
Plug 'https://github.com/majutsushi/tagbar.git'
Plug 'https://github.com/kana/vim-textobj-function.git'
Plug 'https://github.com/nelstrom/vim-textobj-rubyblock.git'
Plug 'https://github.com/kana/vim-textobj-user.git'
Plug 'https://github.com/tomtom/tlib_vim.git'
Plug 'https://github.com/keith/tmux.vim.git'
Plug 'https://github.com/tomtom/viki_vim.git'
Plug 'https://github.com/MarcWeber/vim-addon-async.git'
Plug 'https://github.com/MarcWeber/vim-addon-manager.git'
Plug 'https://github.com/MarcWeber/vim-addon-mw-utils.git'
Plug 'https://github.com/vim-airline/vim-airline.git'
Plug 'https://github.com/vim-airline/vim-airline-themes.git'
Plug 'https://github.com/nvie/vim-flake8.git' " 'pip install flake8'
Plug 'https://github.com/pangloss/vim-javascript.git'
Plug 'https://github.com/preservim/vim-markdown.git'
Plug 'git@github.com:SethMilliken/vim-mtg-spell.git'
Plug 'https://github.com/vim-ruby/vim-ruby.git'
Plug 'https://github.com/derekwyatt/vim-scala.git'
Plug 'https://github.com/mhinz/vim-signify.git'
Plug 'git@github.com:SethMilliken/vim-traitor.git'
Plug 'https://github.com/tmux-plugins/vim-tmux-focus-events.git' " 'set -g focus-events on in tmux'
Plug 'https://github.com/lepture/vim-velocity.git'
Plug 'https://github.com/rkitover/vimpager.git'
Plug 'https://github.com/vim-scripts/vimwiki.git'
Plug 'https://github.com/vim-scripts/vundle.git'
Plug 'https://github.com/vim-scripts/xml.vim.git'
Plug '~/.vim/bundle/vim-morning-pages/'
Plug '~/.vim/bundle/vim-daily-record/'
"Plug 'https://github.com/garbas/vim-snipmate.git'
"Plug 'https://github.com/vim-scripts/UltiSnips.git'
"Plug 'https://github.com/dahu/vimple.git'
"Plug 'https://github.com/Raimondi/vim-pathogen.git'
"Plug 'https://github.com/spf13/snipmate.vim.git'
"Plug 'https://github.com/vim-scripts/AutoTag.git'
"Plug 'https://github.com/wincent/Command-T.git' " 'Rebuild if necessary:\n\tpushd command-t/ruby/command-t/; ruby extconf.rb; make && popd'
"Plug 'https://github.com/rson/vim-conque.git'
"Plug 'https://github.com/godlygeek/csapprox.git'
"Plug 'https://github.com/vim-scripts/dbext.vim.git'
"Plug 'https://github.com/Raimondi/delimitMate.git'
"Plug 'https://github.com/serverhorror/javascript.vim.git'
"Plug 'https://github.com/vim-scripts/jslint.vim.git'
"Plug 'https://github.com/puppetlabs/puppet-syntax-vim.git'
"Plug 'https://github.com/vim-scripts/scala.vim.git'
"Plug 'ssh://seth@at.araxia.net/~/git/script-ed.git'
"Plug 'https://github.com/vim-scripts/StatusLineHighlight.git'
"Plug 'https://github.com/sjl/threesome.vim.git'
"Plug 'https://github.com/vim-scripts/TwitVim.git'
"Plug 'https://github.com/MarcWeber/vim-addon-signs.git'
"Plug 'https://github.com/Lokaltog/vim-powerline.git'
"Plug 'https://github.com/markcornick/vim-vagrant.git'

call plug#end()
" }}}
